"""Alert and queue item model with SLA escalation."""

import uuid
from datetime import datetime, date

from sqlalchemy import String, Text, Float, DateTime, Date, ForeignKey, func
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.dialects.postgresql import UUID, JSONB

from app.models.base import Base, AuditMixin, generate_uuid


class Alert(Base, AuditMixin):
    """
    Alert/queue item generated by predictions, deadline risks, or contradictions.
    Includes priority index, SLA tracking, and escalation.
    """

    __tablename__ = "alerts"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=generate_uuid)
    project_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("projects.id"), nullable=False)
    prediction_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)

    # Alert type and content
    alert_type: Mapped[str] = mapped_column(String(100), nullable=False)
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    severity: Mapped[str] = mapped_column(String(20), default="medium")

    # Priority index (spec Section 10.3)
    priority_index: Mapped[float | None] = mapped_column(Float, nullable=True)
    risk_component: Mapped[float | None] = mapped_column(Float, nullable=True)
    urgency_component: Mapped[float | None] = mapped_column(Float, nullable=True)
    impact_component: Mapped[float | None] = mapped_column(Float, nullable=True)
    actionability_component: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Assignment
    owner_role: Mapped[str | None] = mapped_column(String(100), nullable=True)
    assigned_to: Mapped[str | None] = mapped_column(String(200), nullable=True)
    due_date: Mapped[date | None] = mapped_column(Date, nullable=True)

    # Status
    state: Mapped[str] = mapped_column(String(50), default="open")
    acknowledged_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    acknowledged_by: Mapped[str | None] = mapped_column(String(200), nullable=True)
    snoozed_until: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    snooze_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Recommended action
    recommended_action: Mapped[str | None] = mapped_column(String(50), nullable=True)
    modelled_impact: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    # Metadata
    metadata_json: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
